version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "webgoat-task:1"
        LoadBalancerInfo:
          ContainerName: "webgoat"
          ContainerPort: 8080
